name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'  # triggers only if Terraform files change

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # 1. Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    # 3. Configure AWS credentials
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 4. Terraform init
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # 5. Terraform plan
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan

    # 6. Terraform apply (optional auto-approve)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan
